# Generated by Django 5.2.5 on 2025-10-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveDbCalculating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'main_savedbcalculating',
            },
        ),
        migrations.CreateModel(
            name='SaveDbConsulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'main_savedbconsulting',
            },
        ),
        migrations.DeleteModel(
            name='SaveDb',
        ),
    ]
