# Generated by Django 5.2.5 on 2025-10-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_savedbcalculating_savedbconsulting_delete_savedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbcalculating',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
    ]
