# Generated by Django 5.2.5 on 2025-10-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_savedbcalculating_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedbcalculating',
            name='room_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
