# Generated by Django 5.2.5 on 2025-10-12 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_savedbcalculating_room_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedbcalculating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedbcalculating',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedbcalculating',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='savedbcalculating',
            name='room_area',
            field=models.FloatField(default=10.0),
        ),
    ]
