# Generated by Django 5.2.5 on 2025-10-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_savedbcalculating_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveDbReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('rate', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], default=5)),
            ],
            options={
                'db_table': 'main_savedbreview',
            },
        ),
    ]
