# Generated by Django 5.2.5 on 2025-10-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_savedbreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedbcalculating',
            options={'verbose_name': 'Calculating', 'verbose_name_plural': 'Calculates'},
        ),
        migrations.AlterModelOptions(
            name='savedbconsulting',
            options={'verbose_name': 'Consult', 'verbose_name_plural': 'Consults'},
        ),
        migrations.AlterModelOptions(
            name='savedbreview',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
    ]
