# Generated by Django 5.2.5 on 2025-11-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_savedbcalculating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbconsulting',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
