# Generated by Django 5.2.5 on 2025-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(help_text='Choose project image', upload_to='', verbose_name='Image')),
                ('project_description', models.CharField(help_text='Describe project', max_length=1000)),
            ],
            options={
                'verbose_name': 'Our Project',
                'verbose_name_plural': 'Our Projects',
            },
        ),
    ]
